print("My Daily Routine")
print("Waking up at 5:25")
print("Eat breakfast and get into the car at 6:30")
print("Be at school at 7:20")
print("Talk to my friends in the morning before first period")
print("We have break at 11:00 to 11:30")
print("Home time is at 2:00")
print("I do after school activities like guitar and chess which last till 3:00 or 3:30")
print("I go home freshen up and do my homeworks")
print("I play with my friends outside until sunset")
print("After sunset, I study for 2 hours")
print("I eat dinner")
print("I watch T.V")
print("I read a few pages of a book")
print("I go to sleep at 10:00 PM")